### PR TITLE
Add pole wind susceptibility

### PR DESCRIPTION
**Pull request by dchassin**
Added pole susceptibility property.  It's defined in units per m/s of wind speed.

Note, the PR should be merged after the PR #44 for issue #22 is merged.

### CODE REVIEW

**Comment by jcald1** [comment]
@dchassin , the wind susceptibility value changed at each time step.  I thought this value would be static and only the pole stress would change.

```
# file...... node__HVMV_Sub_LSB_voltage.csv
# date...... Tue Nov 13 21:32:21 2018
# user...... (null)
# host...... (null)
# trigger... (none)
# interval.. 3600
# limit..... 0
# timestamp,climate:wind_speed,node__HVMV_Sub_LSB:nominal_voltage,node__HVMV_Sub_LSB:pole_stress,node__HVMV_Sub_LSB:susceptibility
1973-01-01 00:21:00 PST,+4.14952,+7199.56,+0.00143191,+0.000690158
1973-01-01 01:21:00 PST,+2.58366,+7199.56,+0.000555127,+0.000429721
1973-01-01 02:21:00 PST,+0.83969,+7199.56,+5.86353e-05,+0.000139659
1973-01-01 03:21:00 PST,+0,+7199.56,+0,+0
1973-01-01 04:21:00 PST,+0,+7199.56,+0,+0
1973-01-01 05:21:00 PST,+0,+7199.56,+0,+0
1973-01-01 06:21:00 PST,+0,+7199.56,+0,+0
1973-01-01 07:21:00 PST,+0,+7199.56,+0,+0
1973-01-01 08:21:00 PST,+0,+7199.56,+0,+0
1973-01-01 09:21:00 PST,+0.391464,+7199.56,+1.2744e-05,+6.51093e-05
1973-01-01 10:21:00 PST,+1.50993,+7199.56,+0.000189599,+0.000251136
1973-01-01 11:21:00 PST,+2.65385,+7199.56,+0.000585696,+0.000441394
1973-01-01 12:21:00 PST,+3.69402,+7199.56,+0.0011348,+0.000614399
1973-01-01 13:21:00 PST,+4.45961,+7199.56,+0.00165392,+0.000741734
1973-01-01 14:21:00 PST,+5.20899,+7199.56,+0.00225646,+0.000866372
1973-01-01 15:21:00 PST,+6.2075,+7199.56,+0.00320446,+0.00103245
1973-01-01 16:21:00 PST,+7.32597,+7199.56,+0.00446325,+0.00121847
1973-01-01 17:21:00 PST,+8.03731,+7199.56,+0.00537209,+0.00133679
1973-01-01 18:21:00 PST,+10.841,+7199.56,+0.00977378,+0.00180311
1973-01-01 19:21:00 PST,+15.4094,+7199.56,+0.0197467,+0.00256293
1973-01-01 20:21:00 PST,+20.9031,+7199.56,+0.0363363,+0.00347665
1973-01-01 21:21:00 PST,+21.8915,+7199.56,+0.039854,+0.00364105
1973-01-01 22:21:00 PST,+18.4069,+7199.56,+0.0281762,+0.00306149
1973-01-01 23:21:00 PST,+14.9061,+7199.56,+0.0184778,+0.00247922

```

**Comment by dchassin** [comment]
This is ok. The susceptibility is the first derivative of the moment which is a squared function of wind speed. So we should expect it to be a linear function of wind speed. 

We could just directly calculate the wind speed at failure if that’s what we really need.

**Comment by jcald1** [comment]
@dchassin , that would be great to calculate the wind speed at failure and publish that property, and keep the wind susceptibility property.  The wind speed at failure would be a static value throughout the duration of the simulation?  And this value is the one we could use in a forecast outside of a simulation?

On a related note, it may be worth having the ability to specify whether we want the faults to be triggered by the pole stress > 1 or the wind speed reaching the wind speed failure value. Then we could run two simulations, one for each option, instead of a pole stress simulation plus a forecast of downed poles based on the wind susceptibility.

**Comment by dchassin** [comment]
I’m not sure it would always be static. For example, if ice builds up or the pole tilt changes or the wind direction changes then the failure wind speed could change. Right now it wouldn’t because the model doesn’t consider those. But it will someday if it’s going to be at all useful.

**Pull request merged**
