### PR TITLE
Fix memory leaks in python link

### PR DESCRIPTION
**Pull request by dchassin**
This PR addresses issue with progressive memory leaks detected in the PowerNET simulations. 

## Current issues
1. Fixed verified only for most commonly used calls, e.g., get, get_object, get_value, and set_value.

## Code changes
1. Added a number of `Py_DECREF` calls in the python link.

## Documentation changes
None

## Test and Validation Notes
Create a non-validation test that attempts to consume memory by making the same calls over and over for a very long time. Running this test with `top` running show now significant change in memory use over 100,000+ calls.

### CODE REVIEW

**Comment by aivanova5** [comment]
I found some errors through `validate.py`
~~~
PC95555:python alyona_slac$ python3 validate.py
python3
Validating /Users/alyona_slac/gridlabd/macosx, please wait...
FAIL /Users/alyona_slac/gridlabd/macosx/gldcore/autotest/test_loaderhook_initfailed_err/test_loaderhook_initfailed_err.glm exit 0
/Users/alyona_slac/gridlabd/macosx/gldcore/link/python/gridlabd_python.py(test_loaderhook_initfailed_err.glm) -> exit 0
initialization oktest_loaderhook_initfailed_err.glm(7): ok
FAIL /Users/alyona_slac/gridlabd/macosx/gldcore/autotest/test_string_err/test_string_err.glm exit 0
DEBUG [INIT] : shmkey = 805624842
DEBUG [INIT] : sched_init(): sysconf(_SC_NPROCESSORS_ONLN) = 4
DEBUG [INIT] : checking status of pid 59272
DEBUG [INIT] : module.c:sched_lock(): enter lock[0]=12814220
DEBUG [INIT] : module.c:sched_lock(): exit  lock[0]=12814221
DEBUG [INIT] : module.c:sched_clear(): process_map[n].pid 59272 (proc 0) <- 0
DEBUG [INIT] : module.c:sched_unlock(): enter lock[0]=12814221
DEBUG [INIT] : module.c:sched_unlock(): exit  lock[0]=12814222
DEBUG [INIT] : checking status of pid 0
DEBUG [INIT] : checking status of pid 0
DEBUG [INIT] : checking status of pid 0
DEBUG [INIT] : module.c:sched_lock(): enter lock[0]=12814222
DEBUG [INIT] : module.c:sched_lock(): exit  lock[0]=12814223
DEBUG [INIT] : module.c/sched_allocate_procs(): assigned processor 0 to pid 59277

DEBUG [INIT] : module.c:sched_unlock(): enter lock[0]=12814223
DEBUG [INIT] : module.c:sched_unlock(): exit  lock[0]=12814224
DEBUG [INIT] : GldExec::mls_create()
DEBUG [INIT] : module.c:sched_lock(): enter lock[0]=12814224
DEBUG [INIT] : module.c:sched_lock(): exit  lock[0]=12814225
DEBUG [INIT] : module.c:sched_unlock(): enter lock[0]=12814225
DEBUG [INIT] : module.c:sched_unlock(): exit  lock[0]=12814226
DEBUG [INIT] : object test:0 init -> ok
DEBUG [INIT] : link_initall(): link startup in progress...
DEBUG [INIT] : link_initall(): link startup done ok
DEBUG [INIT] : nObjRankList=0 
DEBUG [INIT] : *** main loop event at 946684800; stoptime=9223372036854775807, n_events=1, exitcode=0 ***
DEBUG [INIT] : module.c:sched_lock(): enter lock[0]=12814226
DEBUG [INIT] : module.c:sched_lock(): exit  lock[0]=12814227
DEBUG [INIT] : module.c:sched_unlock(): enter lock[0]=12814227
DEBUG [INIT] : module.c:sched_unlock(): exit  lock[0]=12814228
DEBUG [INIT] : delta_dt is -2
DEBUG [INIT] : global_clock -> 2000-01-01 00:00:00 UTC

DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_lock(): enter lock[0]=12814228
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_lock(): exit  lock[0]=12814229
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_unlock(): enter lock[0]=12814229
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_unlock(): exit  lock[0]=12814230
DEBUG [2000-01-01 00:00:00 UTC] : *** main loop ended at 9223372036854775807; stoptime=9223372036854775807, n_events=0, exitcode=0 ***
DEBUG [2000-01-01 00:00:00 UTC] : starting dump to gridlabd.glm
DEBUG [2000-01-01 00:00:00 UTC] : dumping properties of 'test' (pmap=0x7fa276f0efb0)
DEBUG [2000-01-01 00:00:00 UTC] : dumping property 'var' of 'test'
DEBUG [2000-01-01 00:00:00 UTC] : dump to gridlabd.glm completed ok (2015 bytes written)
DEBUG [2000-01-01 00:00:00 UTC] : gldcore/exec.c/exec_mls_statewait(): cannot destroy mutex after it was destroyed
DEBUG [2000-01-01 00:00:00 UTC] : gridlabd_main(NULL) returned code 0
/Users/alyona_slac/gridlabd/macosx/gldcore/link/python/gridlabd_python.py(test_string_err.glm) -> exit 0
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_lock(): enter lock[0]=12814230
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_lock(): exit  lock[0]=12814231
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_finish(): process_map[n].state <- DONE
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_unlock(): enter lock[0]=12814231
DEBUG [2000-01-01 00:00:00 UTC] : module.c:sched_unlock(): exit  lock[0]=12814232
DEBUG [2000-01-01 00:00:00 UTC] : exit code 5
DEBUG [2000-01-01 00:00:00 UTC] : exit code 5
Tested.... 648
Failed.... 2
Passed.... 646 (99.7%)
Time...... 619.5 sec
~~~

**Comment by dchassin** [comment]
That’s probably because LD_LIBRARY_PATH is not set to allow loading on the runtime library created by the test.

**Comment by aivanova5** [comment]
Master has the above errors as well.

**Comment by dchassin** [comment]
In that case this is a new issue and probably not related to this PR. We can probably merge this PR regardless. We will need to track down which PR caused these problems.

> Master has the above errors as well.

**Comment by aivanova5** [comment]
What should the LD_LIBRARY_PATH be set to for the loader hook?

**Comment by dchassin** [comment]
I actually don’t think it’s causing the problem. But it should always include the current directory if runtime loaders are used.

> What should the LD_LIBRARY_PATH be set to for the loader hook?

**Comment by dchassin** [comment]
> In that case this is a new issue and probably not related to this PR. We can probably merge this PR regardless. We will need to track down which PR caused these problems.

I've looked into the behavior of `validate.py` and I'm pretty sure it's not working properly.  Also, it's important to note that `validate.py` is not actually testing the python link itself, rather it's testing the ability to simply run the existing validation tests from inside a python session (which is not actually the same thing).

I've open a new issues #351 to track this problem.

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
