### PR TITLE
Issue 52, additional pole properties

### PR DESCRIPTION
**Pull request by aivanova5**
Enhancement of pole object by adding published properties: 

- total_moment
- resisting_moment

Things to be added: 

- wind speed at failure
- the components of the calculation for wind speed at failure

### CODE REVIEW

**Comment by dchassin** [comment]
I will merge after @jcald1 reviews and approves.

**Comment by dchassin** [comment]
@aivanova5 Can you calculate solution to the wind speed at which the resisting moment equals the failure moment and implement that in this branch? When done, reassign it back to @dchassin for review.

**Comment by jcald1** [comment]
@aivanova5 , @dchassin , I didn't see the wind speed at failure  (based on wind susceptibility) in the modhelp or files changed.  If any other components other than wind susceptibility (which is already being outputted) are used in the calculation, then we could record those as well.

**Comment by aivanova5** [comment]
I can publish the components of the calculation (wire moment, equipment moment) in addition to total_moment and resisting_moment (already published). However, you can find the wind speed in the weather object.

**Comment by dchassin** [comment]
@aivanova, I think @jcald is looking for the critical wind speed at which the pole will fail (see above). The problem is it will depend on wind direction once we get that part of the model working.

**Comment by jcald1** [comment]
@dchassin, @aivanova5 , correct, it's the other calculation (critical wind speed at which the pole will fail) and its direct components that we're looking for.

Is wire moment and equipment moment used to calculate total_moment and resisting moment?  It may not hurt to add them as well but I'll leave that up to you.  I'm not sure if we would go beyond using total moment, resisting moment for pole stress, and wind susceptibility for the critical wind speed.  If there are any other direct components for critical wind speed in addition to wind susceptibility, we could publish those as well.

**Comment by dchassin** [comment]
They are used, but equipment has yet to be connected automatically.  Right now, you have to manual add the equipment to the pole.

D



On Nov 15, 2018, at 3:07 PM, Jorge Calderon <notifications@github.com<mailto:notifications@github.com>> wrote:


@dchassin<https://github.com/dchassin>, @aivanova5<https://github.com/aivanova5> , correct, it's the other calculation (critical wind speed at which the pole will fail) and its direct components that we're looking for.

Is wire moment and equipment moment used to calculate total_moment and resisting moment? It may not hurt to add them as well but I'll leave that up to you. I'm not sure if we would go beyond using total moment, resisting moment for pole stress, and wind susceptibility for the critical wind speed. If there are any other direct components for critical wind speed in addition to wind susceptibility, we could publish those as well.

**Pull request merged**
