### PR TITLE
Custom property bugfix

### PR DESCRIPTION
**Pull request by aivanova5**
This PR addresses issue with ambiguous class names and locking error caused by the GRIP `test_model`.

## Current issues
1. None

## Code changes
1. Fixed locking problem on MacOS by changing lock method to METHOD1
2. Added code to detect when class names are ambiguous in loader.

## Documentation changes
None

## Test and Validation Notes
1. Runtime libraries have to be rebuilt during auto test, so you must do a `make distclean -i`.

### CODE REVIEW

**Comment by dchassin** [comment]
This problem arises when the class is modified before the module is loaded.  If this is a concern going forward, I suggest adding an issue to about warnings for ambiguous object statements, i.e., `object class` where `class` is defined more than once, instead of `object module.class`.

**Review by dchassin — COMMENTED** [review]
I think we should probably relocate `test_model.glm` and supporting `data` folder to the existing root auto test folder instead of creating a new `working_model` folder.

**Comment by aivanova5** [comment]
@dchassin Problem with validation: 
~~~
/Users/alyona_slac/gridlabd/macosx/install/bin/gridlabd: line 360: 11636 Segmentation fault: 11  "$bindir/gridlabd.bin" "$@"
ERROR    [INIT] : /Users/alyona_slac/gridlabd/macosx/gldcore/autotest/test_double_array.glm error unexpected, code 139 (unknown exception) in 0.3 seconds
~~~

**Review by dchassin — COMMENTED** [review]
I suggest we close this PR without merging it and work from #256 instead.

**Comment by dchassin** [comment]
Merged into #256 ok.  Ok to close.

**Comment by aivanova5** [comment]
Addressed by PR #256

**Pull request closed without merging**
