### PR TITLE
Add nsrdb geodata package

### PR DESCRIPTION
**Pull request by dchassin**
This PR adds support for NSRBD data in geodata subcommand.

## Current issues

1. It would be nice to have a tutorial on using this package to map weather onto objects.

## Code changes

- [x] Add `gldcore/geodata/geodata_weather.py`.

## Documentation changes

- [x] Use `gridlabd geodata help weather` for online docs on the package.

## Test and Validation Notes

- [x] Unit test include in package (see `gldcore/geodata/autotest/test_datasets.glm`

### CODE REVIEW

**Comment by aivanova5** [comment]
Two errors: 
1. Vague error about not having an API key / registration 
2. Automatic creation of folder .nsrdb/ is not included

**Comment by aivanova5** [comment]
matrix -> array does not work

~~~

aivanovalocal@PC99458 geodata % python3 geodata_weather.py 
ERROR [nsrdb_weather]: unable to get data (too many indices for array: array is 1-dimensional, but 2 were indexed)
E
======================================================================
ERROR: test_weather (__main__.TestWeather)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/share/gridlabd/nsrdb_weather.py", line 236, in getyears
    data = getyear(year,lat,lon)
  File "/usr/local/share/gridlabd/nsrdb_weather.py", line 328, in getyear
    data["datetime"] = list(map(lambda x: datetime.datetime(x[0,0],x[0,1],x[0,2],x[0,3],0,0),numpy.array([data.Year,data.Month,data.Day,data.Hour]).transpose()))
  File "/usr/local/share/gridlabd/nsrdb_weather.py", line 328, in <lambda>
    data["datetime"] = list(map(lambda x: datetime.datetime(x[0,0],x[0,1],x[0,2],x[0,3],0,0),numpy.array([data.Year,data.Month,data.Day,data.Hour]).transpose()))
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aivanovalocal/gridlabd/Nov2021/gldcore/geodata/geodata_weather.py", line 133, in test_weather
    result = apply(test,options=dict(geohash_resolution=6,key_index="name",starttime=starttime,stoptime=stoptime))
  File "/Users/aivanovalocal/gridlabd/Nov2021/gldcore/geodata/geodata_weather.py", line 113, in apply
    weather = nsrdb_weather.getyears(years,lat,lon)
  File "/usr/local/share/gridlabd/nsrdb_weather.py", line 265, in getyears
    error(f"unable to get data ({err})",2)
  File "/usr/local/share/gridlabd/nsrdb_weather.py", line 168, in error
    exit(code)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 2

----------------------------------------------------------------------
Ran 1 test in 0.028s

FAILED (errors=1)
~~~

**Comment by dchassin** [comment]
@aivanova5, I think I've fixed all three problems now. Try again.

**Comment by aivanova5** [comment]
Noting, 

~~~
  CXX      module/powerflow/powerflow_la-node.lo
/private/var/folders/c1/_3xmsmd52jv1_08x4kcb6z_m0000gq/T/build-env-mcvv8pv3/lib/python3.9/site-packages/setuptools/dist.py:507: UserWarning: The version specified ('4.2.30-220120-develop_add_nsrdb_geodata_package\n') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
/private/var/folders/c1/_3xmsmd52jv1_08x4kcb6z_m0000gq/T/build-env-mcvv8pv3/lib/python3.9/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 4.2.30-220120-develop-add-nsrdb-geodata-package- is an invalid version and will not be supported in a future release
  warnings.warn(
  CXX      module/powerflow/powerflow_la-overhead_line_conductor.lo
  CXX      module/powerflow/powerflow_la-overhead_line.lo
  CXX      module/powerflow/powerflow_la-pole.lo
  CXX      module/powerflow/powerflow_la-pole_configuration.lo
/private/var/folders/c1/_3xmsmd52jv1_08x4kcb6z_m0000gq/T/build-env-mcvv8pv3/lib/python3.9/site-packages/setuptools/dist.py:507: UserWarning: The version specified ('4.2.30-220120-develop_add_nsrdb_geodata_package\n') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
~~~

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
