### PR TITLE
[MERGE WITH ISSUES] Implement daemon/remote commands

### PR DESCRIPTION
**Pull request by dchassin**
This enhancement implements a daemon and corresponding remote client to enable local instances of gridlabd to dispatch runs to remote instances.

To start the daemon, use the command gridlabd --daemon start. To stop it use gridlabd --daemon stop.

To ask the daemon to run a simulation, use gridlabd --remote <hostname> <glm-file>. You can also run validate using gridlabd --remote <hostname> --validate.

# Issues

1. Not all commands will return their output. Only output to streams works at this time. Output to stdout and stderr may be lost.

### CODE REVIEW

**Comment by aivanova5** [comment]
BUG merged into master:

[root@f67798825197 source]# gridlabd --daemon start
ERROR    [INIT] : daemon_loadconfig(): [/usr/local/etc/gridlabd.cnf] '  log' not recognized

**Review by aivanova5 — CHANGES_REQUESTED** [review]
Bug reading the .cnf file on docker, see comments.

**Comment by aivanova5** [comment]
@dchassin is this PR ready for review/merge with issues?

**Comment by dchassin** [comment]
@aivanova5: If the problem has been resolved to your satisfaction, then yes it is ready to be merged.  You can also delete the branch after the merge is complete.

**Comment by dchassin** [comment]
The `gridlabd.cnf` should be placed in the `.../share/gridlabd` folder by `make install`.  The default user is the current user.  If running as `root`, the user must be set to a non-root user, or run as `sudo non-root-user`

**Comment by dchassin** [comment]
Note the outstanding issue regarding some output not being routed back to the client.  That should be transferred to the issue list when this PR is closed.

**Pull request merged**
