### PR TITLE
Add fire incident report tool

### PR DESCRIPTION
**Pull request by dchassin**
This PR add support for accessing fire incident report from state regulators.

## Current issues

1. The vegetation geodata set gives an error. (See Issue #1140)
2. SCE and SDGE have invalid report formats for years 2020 and 2016, respectively.  These will have to be handled specially (if at all).

## Code changes

- [x] Add `tools/fire_report.py`

## Documentation changes

- [x] Add [/Tools/Fire_report](http://docs.gridlabd.us/index.html?owner=slacgismo&project=gridlabd&branch=develop-add-fix-incident-report&doc=/Tools/Fire_report.md)

## Test and Validation Notes

- [x] Add `tools/autotest/test_fire_report.{csv,glm}`

### CODE REVIEW

**Comment by dchassin** [comment]
@xiefuhong, the following command results in an unexpected warning:
~~~
$ gridlabd fire_report -y=2021 -u=SCE -s=CA | gridlabd geodata merge -D vegetation > /tmp/test.csv
WARNING [geodata/vegetation]: field of 'latitude' or 'longitude' is missing, use 'nan' for vegetation data.
~~~

**Comment by dchassin** [comment]
@xiefuhong, running as separate commands yields an error:

~~~
$ gridlabd fire_report -y=2021 -u=SCE -s=CA >/tmp/test.csv
$ gridlabd geodata merge -D vegetation /tmp/test.csv
WARNING [geodata/vegetation]: field of 'latitude' or 'longitude' is missing, use 'nan' for vegetation data.
ERROR [geodata/vegetation]: buffer is not large enough
~~~

**Comment by xiefuhong** [comment]
> 

Lat/lon is missing in some records when running `gridlabd fire_report -y=2021 -u=SCE -s=CA | gridlabd geodata merge -D vegetation > /tmp/test.csv`, see line 27, 74 and 86 of the 2021 SCE fire report. This indicated warning message can be removed.

**Comment by xiefuhong** [comment]
> gridlabd geodata merge -D vegetation /tmp/test.csv

This error occurs occasionally and it comes from line 354 of `geodata_vegetation.py`.
`vegetation_data[tifname] = numpy.array(Image.open(dstname))`
This error could be avoid by asking `geodata_vegetation.py` to delete all exiting vegetation image in the cache directory and redownload them if needed.

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
