### PR TITLE
Fix python solver link

### LINKED ISSUE #691: solver_py.conf description error
## Problem description

The solver_py.conf file states that bus data contains voltage magnitudes and angles of the buses (VAm, VAa, ...), but instead it contains the voltage real and imaginary parts (VAr, VAi, ...)

## Steps to reproduce

1. Go to /usr/local/share/gridlabd/solver_py.conf

### LINKED ISSUE #692: solver_py.conf busdump doesn't work
## Problem description

Writing "busdump ./solver_bus.csv" in solver_py.conf is supposed to create a file in which the bus data is dumped, but the file is not created.

## Steps to reproduce
(Explain how to reproduce the behavior, e.g.,)
1. Go to solver_py.conf

### LINKED ISSUE #693: Py_solve segfault when accessing some kwargs of learn() and solve()
## Problem description
kwargs of learn() and solve() methods in solver_py.py have the following keys : ['bustags', 'branchtags', 'busdata', 'branchdata', 'powerflow_type', 'bad_computations', 'iterations']. 
However, only the fourth first keys are accessible, accessing the other ones result in a segmentation fault.

## Steps to reproduce

1. Go to 'solver_py.py'
2. In either learn() or solve() method, write 'print(kwargs["powerflow_type"])' (or bad_computations/iterations)

### LINKED ISSUE #694: Py_solve needs to allow complex values to be copied as magnitude/angle instead of only real/imaginary parts
## Background
The types of voltage passed in the python solver are on the form of real/imaginary part. However, we are interested in predicting the magnitude and angle. 
As for now, when we predict the magnitude and angle, we have to change it back to real and imaginary part to be able to write in the bus data.

## Proposed solution
Express everything as magnitude and angle since we don't really care about real and imaginary parts of the voltage.

## Alternatives
Choose the other description (i.e. real/imaginary). It means the solver will predict the real and imaginary parts instead of magnitude and angle.

### LINKED ISSUE #695: Py_solve needs to allow custom kwargs to be passed from solver_py.conf into solver_py.py methods
## Background
Instead of creating global variable for the type of model used/etc., it would be better to store these variables in kwargs and pass them as GridLAB-D arguments.

## Proposed solution
It would be nice to be able to pass these variables in the .glm file we launch. Or else next to GridLAB-D in the command line, doing something like that : 
`gridlabd IEEE4.glm linear_solver`
`gridlabd IEEE4.glm nn_solver`
if we want to use respectively the linear solver or the neural network.

### PR DESCRIPTION
**Pull request by dchassin**
This PR addresses issue(s) #691, #692, #693, #694, and #695.

## Current issues

1. Causes an exception on IEEE4

## Code changes

- [x] Fix `solver_py.conf` description (#691)
- [x] Fix bus and branch dump (#692)
- [x] Fix copy back errors (#693)
- [x] Add `V[ABC][mad]` copy support (#694)
- [x] Add support for custom `kwargs` entries in `solver_py.conf` (#695)

## Documentation changes

- [x] Document new `option` parameter in `solver_py.conf`

## Test and Validation Notes

- [x] Change `powerflow/autotest/test_IEEE_13_PY.glm` to use `option dump=<type>` to allow `dataframe` or `pretty` dump on `solver()` and `learn()` calls.
- [x] Add `V[ABC][mad]` to `powerflow/autotest/solver_py.conf`

### CODE REVIEW

**Comment by dchassin** [comment]
The `learndata powerflow_values` option in `solver_py.conf` still causes an exception

**Comment by Tom-Achache** [comment]
I’ll look into it.

When pulling the new version, I get this message : Your configuration specifies to merge with the ref 'refs/heads/develop-fix-python-solver-interface'
from the remote, but no such ref was fetched.

Is that a problem?

Tom

**Comment by dchassin** [comment]
Tom, can we close this PR or would you like us to merge it into `develop`?

**Comment by Tom-Achache** [comment]
I don't really know. What do you think would be best ?

**Comment by dchassin** [comment]
Are you actively using the branch version? If so, I think we can merge it into develop given how long you have been using it without trouble.

D.

On Dec 17, 2020, at 16:38, Tom Achache <notifications@github.com> wrote:

﻿

I don't really know. What do you think would be best ?

**Comment by Tom-Achache** [comment]
I just checked the branch I was on and it seems it was "develop-add-pysolver-busname" (so not the one here)

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
