### PR TITLE
[CLOSED] Add support for minimal GLM output.

### PR DESCRIPTION
**Pull request by dchassin**
This PR addresses issue #74.

Current status:

1. The output of values that are default is not always suppressed. This is most often due to values for which the defaults are not set in the class template.
1. None of the transforms are output (so filters won't come through).
1. Schedules are suppressed even when they are defined by the user because there's no way to tell the difference between an internal schedule and a user schedule.
1. A round robin of `models/ieee123` does not give the same result.
1. A sample of the output for `model/ieee123` is attached for reviewer consideration. See [output.glm.zip](https://github.com/dchassin/gridlabd/files/2678049/output.glm.zip)

### CODE REVIEW

**Comment by dpinney** [comment]
Couple thoughts and feedbacks and questions below.

This functionality is very helpful for cleaning up .glms. Not just for GRIP but for a whole bunch of other projects.

But for GRIP, what is the reasoning behind using multiple embedded code features inside the test .glm? Couldn't we solve the parsing and data modeling complexity issues by just using a simpler version of ieee123 and restrict users of the platform from embedding macros and C code in their circuit models? What's the use case for supporting embedded code?

> The output of values that are default is not always suppressed. This is most often due to values for which the defaults are not set in the class template.

I kind of like this, honestly. In the OMF we tend to trust the defaults but don't look at them unless something goes wrong.

> None of the transforms are output (so filters won't come through).

If the transforms are things that look like function calls in the attributes, e.g. "random.triangle(1000,2000)" then those aren't so bad to leave in. They're pretty easy to parse. It's the expansion of one definition in to multiple objects and names derived from functions that are the main pain points.

> Schedules are suppressed even when they are defined by the user because there's no way to tell the difference between an internal schedule and a user schedule... A round robin of models/ieee123 does not give the same result.

These seem like things that could be worked around.

> A sample of the output for model/ieee123 is attached for reviewer consideration. See output.glm.zip

I was able to parse this file successfully with the current version of the OMF parser.

I noticed there were number IDs (e.g. transformer_configuration:29) as well as names (e.g. that objects is also named "tc500"). Why two separate ID systems? Can the numerical ids (which we don't parse) be removed?

**Comment by dchassin** [comment]
> > A sample of the output for model/ieee123 is attached for reviewer consideration. See output.glm.zip
> 
> I was able to parse this file successfully with the current version of the OMF parser.
> 
> I noticed there were number IDs (e.g. transformer_configuration:29) as well as names (e.g. that objects is also named "tc500"). Why two separate ID systems? Can the numerical ids (which we don't parse) be removed?

Object IDs can be removed. But they should not be an issue because they don't conflict with anything.  They are the internal object IDs.  I can make the  NOINTERNALS flag apply to them as well if you want. However, this means that any parent reference to an unnamed object will fail.  I'm not sure that's a good idea.

**Comment by dpinney** [comment]
An option to have the ":id" bits removed would help us out but isn't super important.

**Comment by dchassin** [comment]
> An option to have the ":id" bits removed would help us out but isn't super important.

The choice comes down to whether we want the output to be robust to a potential structural differences on the input.  Nested objects are not used when dumping. But it's possible for an input object which contains a nested object to not have a name.  There no way to detect that such a thing exists until it's too late.  The only solution is to force the output to include the information needed to prevent such an occurrence from causing an error later. 

One thing we can do it use pseudonyms, i.e., if the object has no name, give it the name `class:id`.  Is that ok?

**Comment by dpinney** [comment]
Pseudonyms are a great solution.

I didn't know the dump would remove all embedded objects. That's great. Any code that walks a .glm has a trickier syntax if embedded objects are allowed, so we typically flatten right after parsing.

I also learned today that this version of GridLAB-D offers a .json export. Does that .json have the same structure as the .glm, i.e. a list or other collection of objects?

**Comment by dchassin** [comment]
> I also learned today that this version of GridLAB-D offers a .json export. Does that .json have the same structure as the .glm, i.e. a list or other collection of objects?

The JSON is structured as a `dict`. The primary keys are `application` and `version`, which are used for qualifying the file, and `modules`, `globals`, `classes`, and `objects` which contain the model structure, with subkeys as names, e.g., module name, global name, class name, and object name, respectively.

**Comment by dpinney** [comment]
Interesting. Presence shared a copy of the JSON dumped from the ieee123 system they're using. It looks like everything in the .glm is behind the "objects" key in the JSON, which means with a little scripting this could also enable a full JSON input interface to GridLAB-D. This might let us radically simplify our parser system if we switch to this version of GridLAB-D, so I'll take a look at that.

I'm still of the opinion that the GRIP user interfaces and data models should be restricted to the data in the "minimal GLM" model, but it's not my call to make.

**Comment by dchassin** [comment]
> Interesting. Presence shared a copy of the JSON dumped from the ieee123 system they're using. It looks like everything in the .glm is behind the "objects" key in the JSON, which means with a little scripting this could also enable a full JSON input interface to GridLAB-D. This might let us radically simplify our parser system if we switch to this version of GridLAB-D, so I'll take a look at that.

Note that there are two ways to get the dump.  The first is to use the `json` extension when requesting a dump. The second is to use the server.  There is a minor caveat on the server request: the database may not be entirely self-consistent when the dump is made because the simulation is not paused during the dump.

**Comment by dchassin** [comment]
> I'm still of the opinion that the GRIP user interfaces and data models should be restricted to the data in the "minimal GLM" model, but it's not my call to make.

Are you suggesting the dumps formats like JSON and XML has save options like GLM, i.e., add `xml_save_options` and `json_save_options` just like we added `glm_save_options`?

**Comment by dchassin** [comment]
> Pseudonyms are a great solution.

These have been implement in the latest update to the branch. Consequently the `:id` portion of the object declaration is not omitted when `NOINTERNALS` is in the options (which is included when `MINIMAL` is used.

**Comment by dpinney** [comment]
> Note that there are two ways to get the dump... The second is to use the server.

Good to know. That will enable a nice convenience feature in NRECA's co-simulation code that uses the server.

> Are you suggesting the dumps formats like JSON and XML has save options like GLM, i.e., add xml_save_options and json_save_options just like we added glm_save_options?

No, just suggesting that whatever data model GRIP uses internally for distribution circuits, it should only support objects and attributes that are in the "minimal GLM" data model. I think this will (1) make it easier to manipulate the circuits using other code and (2) map to a GUI that's easier for distribution engineers to use than the full C-like GridLAB-D interface.

**Comment by dchassin** [comment]
Documentation added to https://github.com/dchassin/gridlabd/wiki/glm_save_options

**Comment by dchassin** [comment]
Note that NOINTERNALS support was not yet pushed (the tag was still WORKING).  We can't close this PR yet until those changes are reviewed.

**Pull request merged**
