### PR TITLE
Add fire danger tool

### PR DESCRIPTION
**Pull request by dchassin**
Add support for fire_danger tool to download USGS fire danger maps.

# Code changes

- [x] Add `geodata/geodata_firerisk.py`
- [x] Add `tools\fire_danger.py`

# Documentation

- [x] Add [/Utilities/Fire_danger.md](https://docs.gridlabd.us/index.html?owner=slacgismo&project=gridlabd&branch=develop-add-fire-danger-tool&folder=/Utilities&doc=/Utilities/Fire_danger.md)

# Validation

- [x] Unit test included in `geodata/geodata_firerisk.py`
- [x] Add `tools/autotest/test_fire_danger.glm` and `tools/autotest/test_fire_danger.tif.

### CODE REVIEW

**Comment by ktehranchi** [comment]
I have added the geodata_fireRisk.py package. I saw that Dave added the rasterio package to the requirements.txt document. We may need to add the pyproj package as well since I used that to transform coordinate systems.

**Comment by dchassin** [comment]
> I have added the geodata_fireRisk.py package. I saw that Dave added the rasterio package to the requirements.txt document. We may need to add the pyproj package as well since I used that to transform coordinate systems.

Avoid the use of camel-case in the geodata package names. Using "geodata_firerisk.py" is ok.

**Comment by dchassin** [comment]
@ktehranchi, any thoughts on an autotest we can add to verify this works correctly?

**Comment by ktehranchi** [comment]
> @ktehranchi, any thoughts on an autotest we can add to verify this works correctly?

@dchassin  I wrote a unittest method already at the bottom of the geodata_firerisk.py that checks two GPS coordinates from a specific day against the true values I manually looked up. Is the Autotest different than the unit test? Should I include many more points to make the test a bit more extensive?

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
