### PR TITLE
Fixed issue/1150 (flush not working)

### PR DESCRIPTION
**Pull request by dchassin**
Fix for https://github.com/gridlab-d/gridlab-d/issues/1150 -- Flush isn't working correctly on recorders and collectors.

### CODE REVIEW

**Review by aivanova5 — DISMISSED** [review]
Validation on Docker Centos did not show additional errors.

**Comment by dchassin** [comment]
@aivanova5: Can you devise an autotest that shows flush > 0 is working properly?

**Comment by dchassin** [comment]
@aivanova5: please add the new tests to the tape/autotest folder and reassign back to me to merge into master.

**Comment by dchassin** [comment]
The problem is not fixed yet.  See https://github.com/dchassin/gridlabd/commits/aivanova/recorder_flush for test scripts that show the problem isn't solved.  The file tape_file/tape_file.cpp needs to export flush_recorder, etc. for the flush function to be linked successfully in tape/main.cpp.

**Comment by dchassin** [comment]
This PR is superseded by 
https://github.com/dchassin/gridlabd/pull/11, which corrects the problems found in this one.

**Comment by dchassin** [comment]
This PR is superseded by https://github.com/dchassin/gridlabd/pull/11

**Pull request closed without merging**
