### PR TITLE
[MERGE PROGRESS] Convert gldcore files from C to C++ and fix all reentrancy issues

### PR DESCRIPTION
**Pull request by dchassin**
This PR is a progressive fix to address issue #109. The current implementation is not reentrant. The entire core needs to be rewritten to enable reentrancy. Note that modules may also have reentrancy issues, but these will be dealt with on a case-by-case basis.

To make core reentrant within a single process the following needs to be done. 
1. Convert all gldcore C files to C++.
2. Global static functions need to become methods in classes.
3. Global static variables need to become allocated variables in classes.
4. Identify and eliminate all non-reentrant behavior.
5. Validate with single instance.
6. Validate with multiple instances.

# Status
This processive effort. Merge as work progresses to keep other branches from diverging too far. 
The following have been completed
1. main.c, globals.c, exec.c and cmdarg.c have been converted to C++.
2. main.c, globals, c exec.c, and cmdarg.c static methods are in classes.
3. main.c, globals.c, exec.c, and cmdarg.c static variables are in classes.

# Changes
1. GldMain defined and main.c converted to use GldMain for an instance of gridlabd
2. GldGlobals defined and globals.c converted to use GldGlobals for all globals and environment variables
3. GldExec defined and exec.c converted to use GldExec for all methods and variables
4. GldCmdarg defined and cmdarg.c converted to use GldCmdarg for all methods and variables.

# Testing notes
Start from a clean repo because some of the filenames have changed.  You can either do `make distclean` followed by `autoreconf`, etc.  Or just wipe out the repo and clone it again.

### CODE REVIEW

**Comment by dchassin** [comment]
@aivanova, ready to do first merge to master.  Recommend doing a squashed merge so it shows up as a single commit. Do not close PR after progress is merged.

**Comment by aivanova5** [comment]
Errors on docker on make install: 

~~~
make[1]: *** No rule to make target `gldcore/cmdarg.c', needed by `gldcore/gridlabd_bin-cmdarg.o'.  Stop.
make[1]: Leaving directory `/usr/local/src/gridlabd'
make: *** [install] Error 2
~~~


^^ Addressed by pulling a new image.

**Comment by aivanova5** [comment]
Ready to for merge, checked operation on docker, validates with 100% success rate.

**Comment by dchassin** [comment]
> Errors on make install:
> ~~~
>  make[1]: *** No rule to make target `gldcore/cmdarg.c', needed by `gldcore/gridlabd_bin-cmdarg.o'.  Stop.
>  make[1]: Leaving directory `/usr/local/src/gridlabd'
>  make: *** [install] Error 2
>~~~

Don't forget to `make distclean` when file names change.

**Comment by dchassin** [comment]
Added `daemon.cpp` to the list of files that are done.

**Comment by aivanova5** [comment]
test

**Pull request merged**
