### PR TITLE
Added realtime IEEE 123 model to models folder

### PR DESCRIPTION
**Pull request by dchassin**
This PR adds the IEEE 123 model, ready to run in Bakersfield CA to the models folder.

This should address issue #40.

### CODE REVIEW

**Comment by ryanmmmmm** [comment]
David,

I am trying to run the model but getting mysql errors?

note i am using the gridlabd/slac-master docker image

any thoughts?

Jorge is saying this pull request might fix it?

https://github.com/dchassin/gridlabd/pull/37


venv370) ➜  ieee123 git:(feature/asset_detail_dynamicmodel) ✗ docker run -it -v $(pwd):/model gridlabd/slac-master:latest gridlabd --debug -W /model model/ieee123.glm
ERROR    [INIT] : gldcore/module.c(426): module 'mysql' load failed - libmysqlclient.so.18: cannot open shared object file: No such file or directory
DEBUG [INIT] : gldcore/module.c(427): path to module is '/usr/local/lib/gridlabd/mysql.so'
DEBUG [INIT] : mysql.so: (null) (LD_LIBRARY_PATH=(null))
model/ieee123.glm(144): module 'mysql' load failed, No such file or directory
model/ieee123.glm(144): load failed at or near 'module mysql...'
ERROR    [INIT] : unable to load 'model/ieee123.glm': No such file or directory
FATAL    [INIT] : shutdown after command line rejected

**Comment by aivanova5** [comment]
@ryanmmmmm I believe adding both of these to the path within docker bash should resolve that: 

export PATH=$PATH:/usr/local/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by ryanmmmmm** [comment]
i will try it but i don't see that file in the container i am logged into bash now on it:

/usr/local/lib/gridlabd/mysql.so

**Comment by ryanmmmmm** [comment]
i think we worked through the mysql issues ok for now:

for this model, how can we setup recordings that would output to one CSV file. The current GRIP system is using one CSV output to parse and then present results.

Here is the model we use currently:

https://github.com/PresencePG/grip-server/blob/master/components/grip_sim_runner/simulation_models/ieee8500_swingbus_homes/ieee8500_swingbus_homes.glm

note the recordings. I think we woudl need something similar in the ieee123 but when i try to add a multi recorder i get a class not found error.

`object multi_recorder {
      file 8500_meter_power.csv;
      property HVMV_Sub_HSB:measured_real_power,HVMV_Sub_HSB:measured_voltage_A.real,HVMV_Sub_HSB:measured_voltage_B.real,HVMV_Sub_HSB:measured_voltage_C.real,SX2673305B_1:measured_real_power,SX2673305B_1:measured_voltage_1.real,SX2673305B_1:measured_voltage_2.real,SX2673305B_1:measured_voltage_N.real,SX3048196B_1:measured_real_power,SX3048196B_1:measured_voltage_1.real,SX3048196B_1:measured_voltage_2.real,SX3048196B_1:measured_voltage_N.real;
      interval 15;
      };`

 Let me know your thoughts.

I also assume that Alyona will update this model at a later date with pole data (she has an item to track that but now its with the iee123 model as the first model to provide I guess) but that is not part of this issue/PR.

**Review by aivanova5 — APPROVED** [review]
Additional commits made with mysql.recorder bugs sorted out. ieee123 is running on docker with MySql enabled.

**Pull request merged**
