### PR TITLE
[MERGE PROGRESS] Address reentrancy issues in core

### PR DESCRIPTION
**Pull request by dchassin**
This PR is a progressive fix to address issue #109. The current implementation is not reentrant. The entire core needs to be rewritten to enable reentrancy. Note that modules may also have reentrancy issues, but these will be dealt with on a case-by-case basis.

To make core reentrant within a single process the following needs to be done. 
1. Convert all gldcore C files to C++.
2. Global static functions need to become methods in classes.
3. Global static variables need to become allocated variables in classes.
4. Identify and eliminate all non-reentrant behavior.
5. Validate with single instance.
6. Validate with multiple instances.

# Status
This processive effort. Merge as work progresses to keep other branches from diverging too far. The following have been completed
1. Fixed warnings in `gldcore/daemon.cpp` (257784bec30ab6eb57b132ab9597e9c4ffe5d393)
2. Fixed warnings in `gldcore/convert.cpp` (fc8a62eaee069ed86e256b3c2b0867a00219fb9e)
3. Fixed warnings in `gldcore/validate.cpp` (23f6767aa46d3bb742c6f10aaa147508245db11d) 
4. Fixed warnings in `gldcore/stream.cpp` (1c29c721fa6134e4df8c4b91164d4fecb0fb22f4)
5. And much more (see commits)

# Changes
Numerous

# Testing notes
Start from a clean repo because some of the filenames have changed.  You can either do `make distclean` followed by `autoreconf`, etc.  Or just wipe out the repo and clone it again.

### CODE REVIEW

**Comment by dchassin** [comment]
@aivanova5, leave the PR open after merging, if you can.

**Comment by aivanova5** [comment]
@dchassin Is this ready for a mid-progress review?

**Comment by dchassin** [comment]
Soon

D.

On Mar 27, 2019, at 15:57, Alyona Ivanova <notifications@github.com<mailto:notifications@github.com>> wrote:


@dchassin<https://github.com/dchassin> Is this ready for a mid-progress review?

**Comment by aivanova5** [comment]
Docker failed to install. Looks like the failure is in mysql module.
Screen Shot 2019-03-28 at 10 58 24 AM

**Comment by dchassin** [comment]
Ok. I’ll have to work on that.

D.

On Mar 28, 2019, at 11:02, Alyona Ivanova <notifications@github.com<mailto:notifications@github.com>> wrote:


Docker failed to install. Looks like the failure is in mysql module.
[Screen Shot 2019-03-28 at 10 58 24 AM]<https://user-images.githubusercontent.com/28273120/55181267-94f39f80-5148-11e9-9840-f4878eadec7d.png>

**Comment by aivanova5** [comment]
Install was successful, so I am checking for warnings: 
(1) daemon.cpp still shows warnings as seen in attachment. 
Screen Shot 2019-03-28 at 1 40 20 PM
(2) convert.cpp shows warnings: 
Screen Shot 2019-03-28 at 1 42 28 PM
(3) validate.cpp shows warnings: 
Screen Shot 2019-03-28 at 1 44 17 PM
(4) stream.cpp 
Screen Shot 2019-03-28 at 1 45 31 PM

**Comment by aivanova5** [comment]
Validation on docker: 100% success rate

**Pull request merged**
