### PR TITLE
Add property defaults

### PR DESCRIPTION
**Pull request by dchassin**
This PR addresses issues #89 and #570.

## Current issues
1. Many defaults and flags are still not set. The following modules have not be updated to use the new flags.
  - `generators` (battery, inverter, solar)
  - `market`
  - `mysql`
  - `powerflow`
  - `reliability`
  - `residential`
  - `tape`
2. Output routines should ignore default values.
3. Default needs to be added to runtime class declaration.
4. `enduse` and `loadshape` properties don't propagate flags into sub-properties.

## Code changes
- [X] Change initialization sequence when properties are created so parent class property receive their defaults first.
- [X] Add support for `REQUIRED`, `DYNAMIC`, and `OUTPUT` property flags. 
- [X] Add default, required, dynamic, and output flags to module class property declarations
  - [X] `assert` (assert)
  - [X] `climate` (climate)
  - [x] `commercial` (ceus)
  - [x] `gismo`(line_sensor, switch_coordinator)
  - [X] `industrial` (industrial)
  - [X] `influxdb` (recorder)

## Documentation changes
- [X] [/Command/Example](http://docs-dev.gridlabd.us/_page.html?owner=slacgismo&project=gridlabd&branch=add_property_defaults&folder=/Command&doc=/Command/Example.md)
- [X] [/Command/Modhelp](http://docs-dev.gridlabd.us/index.html)

## Test and Validation Notes
This should have little perceivable effect on the system overall. It may slow down initialization of some larger models. Some outputs will no longer include values that are set to default.

### CODE REVIEW

**Comment by dchassin** [comment]
The order in which properties are initialized must be reversed so that parent class properties are initialized with their defaults before the child class properties are initialized. This is because in some cases a child class has a different default for a property in a parent class.

**Comment by dchassin** [comment]
@evgaston, can you look at the inverter and battery properties and indicate which are required, output, and deprecated?

**Comment by dchassin** [comment]
@kellyye, can you look at the docs to make sure this is going to work for you?

**Comment by dchassin** [comment]
@aivanova5, we need to merge this now in spite of missing some actions because the feature is necessary for the implementation.  The remaining actions relate only to modules that have not yet been upgraded to use this feature.  Let's create new issues for those separate from the addition of support for the defaults, etc.

**Comment by dchassin** [comment]
@kellyye, can you identify which modules and classes you need this feature in the immediate future so we can prioritize the updates?

**Comment by dchassin** [comment]
@aivanova5, this PR is ready to merge.  The current issues need to be copied to new issues.

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
