### PR TITLE
[MERGE WITH ISSUES] Support a gridlabd module in python

### PR DESCRIPTION
**Pull request by dchassin**
This PR introduces the ability to load gridlabd as a module in Python.

## Current issues
1. The `reset` method is not yet implement due to lack of free calls in gldcore after run is completed.
1. `get_transform()` is not yet implement
1. Unit conversion for complex values not yet implemented.
1. Class event handlers cannot be added.
1. There is no way to implement a new GridLAB-D class in python yet. The module needs to define a base class `GldObject` to do that.
1. Object event handlers are only called if there is an event handler already defined for the object's class.
1. Output streams are not flushed immediately so sometimes the messages from different stream appear on stdout and stderr in a different order than they were received.
1. The function `set_global()` does not work before the simulation is started because the core hasn't initialized yet.

## Code changes
1. A few changes in `gldcore` were needed to facilitate integration.  Validate passes 100%.

## Documentation changes
- https://github.com/dchassin/gridlabd/wiki/python

## Test and Validation Notes
1. Only Python 3 is supported.
1. Only basic server calls are supported, e.g., `command`, `start`, `wait`, `cancel`, `pause`, `pauseat`, `resume`, and `[gs]et_{global,value}`. Also have `load`, `save`, and `add` to work with GLM files. Unit conversion utility is available using `convert_unit`. Output streams are accessible.
1. The python module will be built and installed as part of the normal `make` and `make install` processing.
1. You can build and install the gridlabd python module by entering the following command from the top source directory: `python3 gldcore/link/python/setup.py install`.
1. The main build flags `CFLAGS` and `CXXFLAGS` are ignored by `setup.py`.  To change the compiler flags in the python module, you must edit the file `gldcore/link/python/compile_options.py`. The setup script always adds the required flags `-I<build-dir>`, `-DHAVE_PYTHON` and `-DHAVE_CONFIG_H`.

### CODE REVIEW

**Comment by dpinney** [comment]
Very cool.

I think the decision to only support basic server calls is a good one. There's already a lot of ways to interact with GridLAB-D, so keeping this interface extremely close to the HTTP/CL interface seems like a smart way to save effort.

An enhancement request: is there a way to create a GridLAB-D class instead of a module with this Python C extension style? That would enable control of multiple GridLAB-D processes. Not a big deal if this isn't a feature worth pursuing. Syntax example follows:

```python

proc1 = gridlabd.proc(command='test.glm')
proc1.start()

proc2 = gridlabd.proc(command='second_sub.glm')
proc2.start()
...
```

A question: what is the plan for integrating these changes with the PNNL version of GridLAB-D? NRECA needs to decide what version it standardizes on after GLD 4.0.0.

**Review by dpinney — APPROVED** [review]

**Comment by dchassin** [comment]
>An enhancement request: is there a way to create a GridLAB-D class instead of a module with this Python C extension style? That would enable control of multiple GridLAB-D processes.

I really want that too. However much of the core is not reentrant, so we'll have to wait for that upgrade.

**Comment by dchassin** [comment]
> A question: what is the plan for integrating these changes with the PNNL version of GridLAB-D? NRECA needs to decide what version it standardizes on after GLD 4.0.0.

That's up to PNNL. All the improvements in this repo will be part of the code base for the CEC versions of GLOW and HiPAS. Incorporating that into the main release is theoretically part of their subcontract.  However, the branches have diverged quite a bit because we haven't kept up with the FNCS upgrades. I think that's going to be a very challenging merge.

**Comment by jcald1** [comment]
@dchassin , does Python create a subprocess, which starts GridLAB-D in server mode, then all communication is performed using HTTP methods from Python to GridLAB-D?

**Comment by dchassin** [comment]
> @dchassin , does Python create a subprocess, which starts GridLAB-D in server mode, then all communication is performed using HTTP methods from Python to GridLAB-D?

What happens depends on the `start` mode used.  In the cases where the mode requires concurrency, it's a thread, not a forked process.  But you can could use a server process or a daemon process by using the appropriate gridlabd options.

**Comment by dchassin** [comment]
@aivanova5: The code is ready for merge to master.  I suggest you try writing a few simple test cases of your own to see if the wiki and implementation match reasonably well.  Try just running normal models, and try running a model with module event handlers, and a model with object event handlers.

**Review by aivanova5 — CHANGES_REQUESTED** [review]
Errors on install with docker.

**Comment by dchassin** [comment]
The problem in docker has been fixed.

**Comment by aivanova5** [comment]
No problems with the install on docker, 100% validation however models do not load. See error below from the test.glm file as suggested by the example in the python module Wiki: 

>>> gridlabd.start("wait")
  File "test.glm", line 1
    module test;
              ^
SyntaxError: invalid syntax
ERROR    [INIT] : gldcore/exec.c/exec_mls_destroy(): cannot destroy mutex before it was created
Segmentation fault

**Comment by dchassin** [comment]
> > > > File "test.glm", line 1
> > > > module test;
> > > > ^
> > > > SyntaxError: invalid syntax
> > > > ERROR    [INIT] : gldcore/exec.c/exec_mls_destroy(): cannot destroy mutex before it was created
> > > > Segmentation fault

This problem is addressed by a recent fix in the branch `dchassin/python`.

**Pull request merged**
