### PR TITLE
Implement json_dump facilities

### PR DESCRIPTION
**Pull request by dchassin**
A new file format ".json" is now supported for output only.  The `-o filename.json` command line option and the server `/json/filename.json` HTTP query are supported.

Note that the loader does not support JSON input at this time.

### CODE REVIEW

**Comment by dchassin** [comment]
The command line dump option is completed.  It is automatically selected based on the file name extension ".json".  Attached is the output of the new autotest file.
[output.json.zip](https://github.com/dchassin/gridlabd/files/2521106/output.json.zip)

**Comment by dchassin** [comment]
The server supports JSON dumps using the syntax
~~~
hostname% curl http://localhost:6267/json/*
~~~

**Comment by jcald1** [comment]
I'm getting a compile error on this branch

```
jorge@ubuntu:~/gridlabd$ make install
/bin/bash -c "source utilities/build_number . gldcore/build.h"
/home/jorge/gridlabd
(git remote -v ; git log -n 1 ; git status -s ; git diff ) > origin.txt
make  install-am
make[1]: Entering directory '/home/jorge/gridlabd'
  CXX      climate/climate_climate_la-init.lo
In file included from /usr/include/c++/7/vector:60:0,
                 from climate/climate.h:17,
                 from climate/init.cpp:11:
/usr/include/c++/7/bits/stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
/usr/include/c++/7/bits/stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
In file included from ./gldcore/gridlabd.h:91:0,
                 from climate/init.cpp:9:
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected unqualified-id before ‘const’
     min(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:195:5: error: expected initializer before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected unqualified-id before ‘const’
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected ‘)’ before ‘const’
/usr/include/c++/7/bits/stl_algobase.h:219:5: error: expected initializer before ‘const’
In file included from /usr/include/c++/7/vector:60:0,
                 from climate/climate.h:17,
                 from climate/init.cpp:11:
/usr/include/c++/7/bits/stl_algobase.h:246:7: error: expected primary-expression before ‘if’
       if (__comp(__b, __a))
       ^~
/usr/include/c++/7/bits/stl_algobase.h:246:7: error: expected ‘}’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:246:7: error: expected ‘;’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:248:7: error: expected unqualified-id before ‘return’
       return __a;
       ^~~~~~
/usr/include/c++/7/bits/stl_algobase.h:268:7: error: expected primary-expression before ‘if’
       if (__comp(__a, __b))
       ^~
/usr/include/c++/7/bits/stl_algobase.h:268:7: error: expected ‘}’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:268:7: error: expected ‘;’ before ‘if’
/usr/include/c++/7/bits/stl_algobase.h:270:7: error: expected unqualified-id before ‘return’
       return __a;
       ^~~~~~
/usr/include/c++/7/bits/stl_algobase.h:271:5: error: expected declaration before ‘}’ token
     }
     ^
Makefile:5338: recipe for target 'climate/climate_climate_la-init.lo' failed
make[1]: *** [climate/climate_climate_la-init.lo] Error 1
make[1]: Leaving directory '/home/jorge/gridlabd'
Makefile:7132: recipe for target 'install' failed
make: *** [install] Error 2
```

```
jorge@ubuntu:~/gridlabd$ git branch
* dchassin/json_dump
  master
jorge@ubuntu:~/gridlabd$ git log
commit f0c9269403edffd7a91524ba0edbc56a2f958e1c (HEAD -> dchassin/json_dump, origin/dchassin/json_dump)
Author: David P. Chassin <dchassin@slac.stanford.edu>
Date:   Fri Oct 26 15:44:48 2018 -0700

    Added support for json HTTP queries to server


```

**Comment by dchassin** [comment]
This looks like a conflict between the min/max macros in platform.h and the STL on ubuntu.  This doesn't happen on Centos or macOS. Unfortunately, I don't have a working ubuntu system on docker yet.  Can you post the ubuntu setup script you use to build your system so that I can replicate it on docker?

**Review by ryanmmmmm — COMMENTED** [review]
David,

Do you have a few sample output  json files you are validating against you could share with us? I do not see any in this commit.

**Comment by jcald1** [comment]
This is on a non Docker Ubuntu environment.

> sudo apt-get update
> sudo apt install build-essential libxerces-c-dev

> jorge@ubuntu:~/projects/grip/grip-server$ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3.2' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2) 
> 
> 
> jorge@ubuntu:~/projects/grip/grip-server$ make -v
> GNU Make 4.1
> Built for x86_64-pc-linux-gnu
> Copyright (C) 1988-2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
>

> jorge@ubuntu:~/projects/grip/grip-server/components/grip_sim_runner/simulation_models/ieee8500_pole_vulnerability$ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 17.10
> Release:	17.10
> Codename:	artful
>

**Comment by jcald1** [comment]
I was able to replicate this with Docker.  Below is the Dockerfile.

```
FROM library/python:3.7-stretch

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

# RUN apt-get install -y postgresql-client

# For VIM
RUN apt-get install -y apt-file
RUN apt-file update
RUN apt-get install -y vim

# RUN pip install --upgrade pip

# COPY requirements.txt /
# RUN pip3 install --trusted-host pypi.org -r /requirements.txt

# Setup GridLAB-D
RUN apt-get install -y libxerces-c-dev automake cmake libboost-all-dev  build-essential
WORKDIR /
#RUN git clone https://github.com/gridlab-d/gridlab-d.git
RUN git clone -b dchassin/json_dump https://github.com/dchassin/gridlabd.git
WORKDIR /gridlabd
RUN pwd
RUN autoreconf -if
RUN ./configure --enable-silent-rules 'CFLAGS=-g -O0 -w' 'CXXFLAGS=-g -O0 -w' 'LDFLAGS=-g -O0 -w'
RUN make
RUN make install

# WORKDIR /code

CMD ["gridlabd" "--version"]
```

**Comment by dchassin** [comment]
This contains a simple GLM and the corresponding JSON file.

[test_json.zip](https://github.com/dchassin/gridlabd/files/2526770/test_json.zip)

**Comment by jcald1** [comment]
It looks like the JSON has duplicate keys ("size").  Do you have any samples with object names populated?

```

		"refrigerator": {
			"size": "1432",
			"parent": "residential_enduse",
			"trl": "0",
			"profiler.numobjs": "0",
			"profiler.clocks": "0",
			"profiler.count": "0",
			"size": {
				"type": "double"
			},
```

**Comment by jcald1** [comment]
The attached GLM file looks fine but when running an IEEE8500 file, the output is invalid. It looks like the triplex_node:4582 object is closed with a "}" but not the node_X2730107C object.  This is assuming that the next node (node_X3048888C) is supposed to be at the same level as the previous node.  The same issue occurs with the other node/triplex_node combinations.  The IEEE8500 GLM file is attached.
[ieee8500_swingbus_homes.zip](https://github.com/dchassin/gridlabd/files/2550481/ieee8500_swingbus_homes.zip)


```
		"node_X2730107C" : {
		"triplex_node:4582" : {
			"class" : "triplex_node",
			"id" : "4582",
			"rank" : "5",
			"clock" : "4273280",
			"schedule_skew" : "0",
			"rng_state" : "284122032",
			"heartbeat" : "0",
			"guid" : "0x24275f2a8d71522",
			"flags" : "0x100",
			"bustype" : "PQ",
			"busflags" : "HASSOURCE",
			"reference_bus" : "",
			"maximum_voltage_error" : "+0.012 V",
			"voltage_1" : "+123.018+88.7837d V",
			"voltage_2" : "+123.018+88.7837d V",
			"voltage_N" : "+0+0j V",
			"voltage_12" : "+246.035+88.7837d V",
			"voltage_1N" : "+123.018+88.7837d V",
			"voltage_2N" : "+123.018+88.7837d V",
			"current_1" : "+0+0i A",
			"current_2" : "+0+0i A",
			"current_N" : "+0+0i A",
			"current_1_real" : "+0 A",
			"current_2_real" : "+0 A",
			"current_N_real" : "+0 A",
			"current_1_reac" : "+0 A",
			"current_2_reac" : "+0 A",
			"current_N_reac" : "+0 A",
			"current_12" : "+0+0i A",
			"current_12_real" : "+0 A",
			"current_12_reac" : "+0 A",
			"power_1" : "+0+0i VA",
			"power_2" : "+0+0i VA",
			"power_12" : "+0+0i VA",
			"power_1_real" : "+0 W",
			"power_2_real" : "+0 W",
			"power_12_real" : "+0 W",
			"power_1_reac" : "+0 VAr",
			"power_2_reac" : "+0 VAr",
			"power_12_reac" : "+0 VAr",
			"shunt_1" : "+0+0j S",
			"shunt_2" : "+0+0j S",
			"shunt_12" : "+0+0j S",
			"impedance_1" : "+0+0i Ohm",
			"impedance_2" : "+0+0i Ohm",
			"impedance_12" : "+0+0i Ohm",
			"impedance_1_real" : "+0 Ohm",
			"impedance_2_real" : "+0 Ohm",
			"impedance_12_real" : "+0 Ohm",
			"impedance_1_reac" : "+0 Ohm",
			"impedance_2_reac" : "+0 Ohm",
			"impedance_12_reac" : "+0 Ohm",
			"house_present" : "FALSE",
			"GFA_enable" : "FALSE",
			"GFA_freq_low_trip" : "+59.5 Hz",
			"GFA_freq_high_trip" : "+60.5 Hz",
			"GFA_volt_low_trip" : "+0.8 pu",
			"GFA_volt_high_trip" : "+1.2 pu",
			"GFA_reconnect_time" : "+300 s",
			"GFA_freq_disconnect_time" : "+0.2 s",
			"GFA_volt_disconnect_time" : "+0.2 s",
			"GFA_status" : "TRUE",
			"service_status" : "IN_SERVICE",
			"service_status_double" : "-1",
			"previous_uptime" : "-1 min",
			"current_uptime" : "+10 min",
			"topological_parent" : "",
			"frequency_measure_type" : "NONE",
			"sfm_Tf" : "+0.01 s",
			"pll_Kp" : "+10 pu",
			"pll_Ki" : "+100 pu",
			"measured_angle_1" : "+0 rad",
			"measured_frequency_1" : "+60 Hz",
			"measured_angle_2" : "+0 rad",
			"measured_frequency_2" : "+60 Hz",
			"measured_angle_12" : "+0 rad",
			"measured_frequency_12" : "+60 Hz",
			"measured_frequency" : "+60 Hz"
		},
		"node_X3048888C" : {
		"triplex_node:4583" : {
			"class" : "triplex_node",
			"id" : "4583",
                        ...
```

**Comment by dchassin** [comment]
Sure enough there were several problems revealed by the 8500 bus model.  They have been fixed.

**Review by aivanova5 — APPROVED** [review]
Checked the branch on a docker system with IEEE8500 model  - no apparent issues found.

**Review by jcald1 — APPROVED** [review]

**Pull request merged**
