### PR TITLE
[MERGE WITH ISSUES] Add support for defaults to be handled in JSON and GLM dumps

### PR DESCRIPTION
**Pull request by dchassin**
This PR addresses issue(s) arras-energy/gridlabd-old#74. This PR arras-energy/gridlabd-old#81.

The big improvement is that the output minimal GLM loads and runs properly for the IEEE123 model.

## Current status
1. The output of values that are default is not always suppressed. This is most often due to values for which the defaults are not set in the class template.
1. None of the transforms are output (so filters won't come through).
1. Schedules are suppressed even when they are defined by the user because there's no way to tell the difference between an internal schedule and a user schedule.
1. A round robin of models/ieee123 does not give the same result.
1. A sample of the output for model/ieee123 is attached for reviewer consideration.
1. Not all the classes have been converted to use the new "X_init()" form of property initialization.

## Code changes
1. Numerous internal core changes
1. New method of setting defaults introduced in climate and powerflow. (Needs to be propagated to all other classes.)

## Documentation changes
(none)

## Test and Validation Notes
1. A copy of the IEEE123 model outputs in JSON and minimal GLM is attached
[ieee123.zip](https://github.com/dchassin/gridlabd/files/2692504/ieee123.zip)
.

### CODE REVIEW

**Comment by aivanova5** [comment]
Multi-line feature in multi-recorder is not working with this implementation. 
File attached for reference. 
[ieee123_pole_vulnerability.glm.zip](https://github.com/dchassin/gridlabd/files/2692759/ieee123_pole_vulnerability.glm.zip)

**Review by dpinney — APPROVED** [review]
Towards a cleaner GLD add-on ecosystem.

**Comment by aivanova5** [comment]
@dchassin I am getting major segmentation fault errors in assert, commercial, generators, gldcore
 etc modules of this branch during validation. 

[validate.txt](https://github.com/dchassin/gridlabd/files/2765760/validate.txt)

**Comment by dchassin** [comment]
@aivanova5 , this is clearly not ready to be merged yet.  I'll resume work on it and let you know when I'm done.

**Comment by aivanova5** [comment]
@dchassin I am still seeing errors in validation. For example: 

ERROR    [INIT] : /poles/source/assert/autotest/test_double_assert.glm exception unexpected, code 255 (exception caught) in 5.5 seconds
UNHANDLED EXCEPTION: write lock timeoutt_double_assert_err.glm...
UNHANDLED EXCEPTION: write lock timeoutt_enum_assert.glm...    


This error applies to a number of modules.

**Comment by aivanova5** [comment]
Passed validation with 100%, merging into master.

**Comment by dchassin** [comment]
Carried forward issues into arras-energy/gridlabd#85.

**Pull request merged**
