### PR TITLE
Fix python callback failures on some platforms

### PR DESCRIPTION
**Pull request by dchassin**
This PR addresses issue #674 
 
## Current issues
1. The fixes do not work on docker images based on Python 3.6. This requires that all the docker base images be updated to Python 3.7.  Some have not yet been updated.

## Code changes
- [x] Fix invalid callback return value when callback function is not found.
- [x] Fix `PYTHONPATH` in `gridlabd` main start script.

## Documentation changes
None

## Test and Validation Notes
None

### CODE REVIEW

**Comment by dchassin** [comment]
The problem seems to be caused by another python module called `test` that is found first on some platforms.  As a workaround, try renaming the `test.py` module to use a name that does not conflict with any modules installed in the python libraries.  Use `my_test.py` works fine. 

In the meantime, we're going to look at creating a way to directly control the search path for python modules when using GridLAB-D as the environment.

**Comment by dchassin** [comment]
The issue seems to be that the docker image that fails is using `python3.6` instead of `python3.7`.  Python36 loads a new instance of the `gridlabd` module into python instead of linking the internal one like Python37 does.

The solution may be to upgrade all docker images to Python37 using https://www.workaround.cz/howto-compile-install-latest-python-37-38-39-centos-7-8/. This requires installing `zlib`, e.g., `yum install zlib-devel`. 

It also requires installing `python3.7.7-devel`, which isn't generally available yet.

**Comment by dchassin** [comment]
@aivanova5, can you look how to upgrade the docker base images so they are all python3.7? While we're doing this update, we need to incorporate the updates listed the current `.circleci/config.yml`.

**Comment by dchassin** [comment]
The following script fixes the docker hub image `slacgismo/gridlabd:develop`:

~~~
dnf install gcc openssl-devel bzip2-devel libffi-devel -y
yum install -y xz-devel -y
cd /usr/local/src
curl https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz > Python-3.7.7.tgz
tar xzf Python-3.7.7.tgz
cd Python-3.7.7
./configure --enable-optimizations
make altinstall
ln -sf /usr/local/bin/python3.7 /usr/local/bin/python3
ln -f /usr/local/bin/python3.7m-config /usr/local/python3-config
ln -s /usr/local/bin/pyvenv-3.7 /usr/local/bin/pyvenv
/usr/local/bin/python3 -m pip install matplotlib Pillow pandas numpy
cd /usr/local/src
rm -f Python-3.7.7.tgz
~~~

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
