### PR TITLE
[REVIEW] Moving pole calculations from pre-sync to init.

### PR DESCRIPTION
**Pull request by aivanova5**
Shifting the pole stress and moment calculations into init rather than presync.

### CODE REVIEW

**Comment by aivanova5** [comment]
Note, pull from master first before merging due to PR #94

**Comment by dchassin** [comment]
@aivanova5, I don't think this is going to work as expected.   We need to separate the time-dependent things (e.g., function of wind) that stay in presync(), from time-independent things that move to init().

**Review by dchassin — CHANGES_REQUESTED** [review]
Move time-dependent elements of the model to presync().  Leave the time-independent elements in init().

**Comment by aivanova5** [comment]
@dchassin ready for second round of reviews.

**Comment by dchassin** [comment]
Validation passed 100% on Mac OSX and Centos docker.

**Pull request merged**
