### PR TITLE
Fix python module build method

### LINKED ISSUE #986: Upgrade needed to python module build
## Problem description

The following message now appears when building gridlabd:

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will 
no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see 
discussion at https://github.com/Homebrew/homebrew-core/issues/76621.

### PR DESCRIPTION
**Pull request by dchassin**
This PR fixes issue #986.

## Current issues

1. The wheel name does not conform to PEP 440 standard.
2. This PR to the build method doesn't make the deprecation error go away. However, it does bring the build method up to PEP 440 standards, which is important.

## Code changes

- [x] Fix `gldcore/link/python/{Makefile.mk,setup.py}` to use python build module instead of disttools.

## Documentation changes

None

## Test and Validation Notes

You may notice warning errors about the version name not conforming to the PEP 440 standard.  This is not a problem. Yet.

### CODE REVIEW

**Comment by aivanova5** [comment]
~~~
Found existing installation: gridlabd 4.2.30.220112
ERROR: Cannot uninstall 'gridlabd'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
~~~

**Review by aivanova5 — CHANGES_REQUESTED** [review]
Makefile.mk contains line `@python3 -m pip uninstall gridlabd -y` which breaks `make reconfigure` on Darwin

~~~
Found existing installation: gridlabd 4.2.30.220112
ERROR: Cannot uninstall 'gridlabd'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
~~~

**Comment by dchassin** [comment]
> Makefile.mk contains line `@python3 -m pip uninstall gridlabd -y` which breaks `make reconfigure` on Darwin
> 
> ```
> Found existing installation: gridlabd 4.2.30.220112
> ERROR: Cannot uninstall 'gridlabd'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> ```

This error will only occur if you use `make reconfigure` or `make clean` on an build made with the older python build method.  Use `. utilities/cleanwc` followed by `autoreconf -isf && ./configure` instead to avoid this transient problem. A message to that effect has been added to the makefile when that error occurs.

**Comment by dchassin** [comment]
Unfortunately, this change to the build method doesn't make the deprecation error go away. This was the ultimately objective of the PR. However, it does bring the build method up to PEP 440 standards, which is important.

**Review by aivanova5 — APPROVED** [review]

**Pull request merged**
