### PR TITLE
[WORKING] Implemented solution to #14 -- randomseed not recoverable

### PR DESCRIPTION
**Pull request by dchassin**
#### What's this Pull Request do?
This PR makes randomstate a global variable and separates it from randomseed so that randomseed is left untouched for the duration of the simulation. 
#### Where should the reviewer start?
Use the attached files to see if the randomseed can be saved and restored from one run to the next.
[issue_14.zip](https://github.com/dchassin/gridlabd/files/2489049/issue_14.zip)
#### How should this be tested?
After the fix, the same seed should come up each time.
#### Any background context you want to provide?
No.
#### What are the relevant issues?
There is a question about whether the randomstate is also saved and restored.  The fix proposed allows the randomstate to be set also, which allow the random number generation to resume where it left off without falling back on the original seed value.
#### Screenshots (if appropriate)
None.
#### Questions:
- [ ] Does this add new dependencies?
- [ ] Is there appropriate logging included?

### CODE REVIEW

**Review by aivanova5 — CHANGES_REQUESTED** [review]
[issue_14-r3.zip](https://github.com/dchassin/gridlabd/files/2511602/issue_14-r3.zip)

Randomseed is not working as expected, see the issue for more info. The updated test_file is attached.

**Comment by jcald1** [comment]
In the save_randomstate, I added:

```
echo "randomstate: $randomstate"
echo "randomseed: $randomseed"
```

The randomstate isn't printing out.

How can I print out the value of x at each step?  I added

> script export x;

to the glm and 

> echo "x: $x"

 in the save_randomstate command, but I don't see any output for x.

I included  

> -o output.xml

 in the gridlab command and the output .xml file contains:
```
	<randomseed>3160364114</randomseed>
	<randomstate>3160364114</randomstate>
```

so it doesn't look like the random state has changed during the simulation run.

**Comment by dchassin** [comment]
The problem with randomstate not updating seems to be associated with the behavior of putenv.  Replaced putenv with setenv, which seems to have addressed the issue.

**Review by aivanova5 — CHANGES_REQUESTED** [review]
Inconsistency with docker implementation of the random state. When deleting the seed and running the test_random.glm file again, the seed is saved correctly every time but state doesn't save correctly every time - only every other time. 

Terminal output is attached, the tail of the file contains version and origin information. The first run generates a seed and state, the next run generates the same state. When the seed is regenerated the second run has different states from the first run. 

[terminal_output_issue14.txt](https://github.com/dchassin/gridlabd/files/2531005/terminal_output_issue14.txt)

**Comment by dchassin** [comment]
The problem has been fixed by PR #199.  Closing this PR.

**Pull request closed without merging**
