### PR TITLE
Update PG&E residential tariffs

### PR DESCRIPTION
**Pull request by HectorTR**
Updated tariffs

This PR fixes issue #NUMBER1.

## Current issues
1. list all open problems and questions related to this PR.
1. the PR status should `DRAFT` until this entire list is resolved.
1. if a merge is ok with the current issues, then create new issues from this list.

## Code changes
- [x] List significant code changes

## Documentation changes
- [x] [<<<DOCSPEC>>>](http://docs.gridlabd.us/index.html?owner=slacgismo&project=gridlabd&branch=<<<BRANCHNAME>>>&doc=<<<DOCPATHNAME>>>)

## Test and Validation Notes
- [x] List changes to existing autotests
1. Enumerate any testing and validation considerations.

### CODE REVIEW

**Comment by dchassin** [comment]
Are these changes for the rate as of 1 Mar 2020?

**Comment by HectorTR** [comment]
Hi Dave, I downloaded them a week ago.

I'm working on the other rates as well, but I had a hard time understanding
a few pieces of it.

Hector

**Review by dchassin — CHANGES_REQUESTED** [review]
The problem with README.md was addressed by merging the baseline branches.

**Comment by dchassin** [comment]
Please do not change the 200301 tariffs unless they are wrong.  Please put the current tariff in a new file with a similar name such that the starting date of the tariff is used as YYMMDD, e.g., `pgande_res_201001.glm`.

**Pull request merged**
