### PR TITLE
Add percent done to progress output

### PR DESCRIPTION
**Pull request by dchassin**
This PR fixes issue #569.

## Current issues
None

## Code changes
- [X] Add percent done to progress report output
- [X] Add validate `keep_progress` usage
- [X] Add access to `keep_progress` global

## Documentation changes
- [X] Document `keep_progress` global

## Test and Validation Notes
Both running progress and validate output now support `-D keep_progress=TRUE`.

### CODE REVIEW

**Comment by aivanova5** [comment]
Could you post a screenshot of where the progress % will show up? I am not seeing it while testing.

**Comment by dchassin** [comment]
Try the following command:

~~~
bash$ gridlabd -W residential/autotest/test_HVAC_common_cool test_HVAC_common_cool.glm -D show_progress=TRUE -D keep_progress=TRUE -D suppress_repeat_messages=FALSE
~~~

It should generate the following output:
~~~
WARNING  [INIT] : /usr/local/opt/gridlabd/4.2.1-200316-develop_add_percent_progress/share/gridlabd/tzinfo.txt(170): timezone spec 'PST0PDT' not found in 'tzinfo.txt', will include no DST information
Processing 2001-07-24 02:03:31 PST (4.4% done)...
Processing 2001-07-24 07:28:06 PST (26.9% done)...
Processing 2001-07-24 12:58:48 PST (49.9% done)...
Processing 2001-07-24 18:34:25 PST (73.2% done)...
Processing 2001-07-25 00:10:17 PST (96.5% done)...
~~~

If you are referring to the output in `gridlabd.prg`, that is not what I understood was requested, but that is easily supported too.

**Comment by aivanova5** [comment]
What is the "show_progress" global? 
Also, should the expected progress report be repeatable (ie same % values every time)?

~~~
PC95555:test_HVAC_common_cool alyona_slac$ gridlabd -D keep_progress=TRUE -D suppress_repeat_messages=FALSE test_HVAC_common_cool
WARNING  [INIT] : /usr/local/opt/gridlabd/4.2.1-200317-develop_add_percent_progress/share/gridlabd/tzinfo.txt(170): timezone spec 'PST0PDT' not found in 'tzinfo.txt', will include no DST information
Processing 2001-07-24 05:47:49 PST (20.0% done)...
Processing 2001-07-24 12:04:55 PST (46.2% done)...
Processing 2001-07-24 18:14:31 PST (71.8% done)...
Processing 2001-07-25 00:17:54 PST (97.1% done)...
PC95555:test_HVAC_common_cool alyona_slac$ gridlabd -D keep_progress=TRUE -D suppress_repeat_messages=FALSE test_HVAC_common_cool
WARNING  [INIT] : /usr/local/opt/gridlabd/4.2.1-200317-develop_add_percent_progress/share/gridlabd/tzinfo.txt(170): timezone spec 'PST0PDT' not found in 'tzinfo.txt', will include no DST information
Processing 2001-07-24 03:42:53 PST (11.3% done)...
Processing 2001-07-24 08:46:27 PST (32.4% done)...
Processing 2001-07-24 15:11:53 PST (59.1% done)...
Processing 2001-07-24 22:17:17 PST (88.7% done)..
~~~

**Comment by dchassin** [comment]
> What is the "show_progress" global?

The `show_progress` global enables display of the progress report (usually it's default `TRUE`)

**Comment by dchassin** [comment]
> Also, should the expected progress report be repeatable (ie same % values every time)?

No, it depends on many system loading/cpu/memory/disk etc variables that change from one run to another.  Progress is output periodically based on wall clock time, not simulation time.

**Comment by aivanova5** [comment]
One more thought on this, should the `suppress_repeat_messages` global set to `FALSE` be a prerequisite for `keep_progress`? Otherwise, the progress is not very informative.

**Comment by dchassin** [comment]
Good idea. I'll change the progress output that keeps progress to use a call that ignores the value of `suppress_repeat_messages`/

**Review by aivanova5 — APPROVED** [review]

**Review by aivanova5 — APPROVED** [review]

**Comment by yeyanzhu** [comment]
The progress output will not display 100% done. Is it possible to also display the last step (100% done) in the progress output?

**Comment by dchassin** [comment]
@yeyanzhu, I'm curious what are you trying to achieve.  If you are reading the progress output to get the status of the simulation run, there are much better ways to get that information that reading a relatively unreliable output stream.  
1. You can use the REST API, which provides access to several global variable such as the clock and the main loop state.  
1. You can use the process status command option, which returns information on all the active and recently completed simulations.
1. You can read the shared memory map directly, which include all the information used by the process status.

**Comment by yeyanzhu** [comment]
Hi David, We intends to monitor the simulation progress, display the progress or status on the front-end UI. The initial thought is to create APIs to read those output streaming files, e.g. err, warning, progress, etc. The front-end UI will query these information through these APIs.

**Comment by dchassin** [comment]
You should look at how the IEEE-123 realtime simulator does this using the existing server REST API.  You can also monitor progress using the python gridlabd module.  Using the progress stream is not reliable because the model can change how that stream works.

**Comment by yeyanzhu** [comment]
Thanks, David. Can you provide the reference link for these two approaches? And does it mean that the GridLAB-D needs to be run on server mode to make the server REST API works?

**Pull request merged**
