### PR TITLE
Fix the autotest failure due to TMY2 use instead of TMY3

### PR DESCRIPTION
**Pull request by aivanova5**
This PR addresses issue(s) of `test_err_solar_parent.glm` failing due to wrong usage of TMY2 file rather the target failure of misuse of parent object with solar object. 

## Current issues
TMY3 fix is in however this test still doesn't differentiate between bad parent error and other errors.

## Code changes
1. `generators/autotests/test_err_solar_parent.glm`

## Documentation changes
- N/A

## Test and Validation Notes
1. Run gridlabd --validate

### CODE REVIEW

**Review by dchassin — APPROVED** [review]

**Comment by dchassin** [comment]
@aivanova5, anything further on this, or is it ready for review?

**Comment by aivanova5** [comment]
@dchassin Trying to think of a creative way to test for the exact error but no luck yet.

**Comment by dchassin** [comment]
@aivanova5, isn't TMY2 usage a warning right now?  Do you want me to change it to an error?

**Comment by dchassin** [comment]
(Oops. I meant to delete my comment.). We're still looking for a creative to get this error.

**Pull request merged**
